extends Node
#Email formats follow this format:
# Key:{list of items}
# subject:{from, email, text, links}
var emails = {
	"Welcome Newbie":{"from":"Stephen Careers", "email":"scareers@digs.org", "text":"Hey there, newbie. Thanks for picking up the position as my trusty secretary. This job is a piece of cake; just forward the important stuff to me and delete anything unimportant or malicious. I don’t want my inbox cluttered with spam and nasty viruses. Just be careful: scammers nowadays are always hiding in plain sight.\n\nI’m sure you’ll do great. Go ahead and delete this email.\n– Your Boss, Stephen Careers","links":"","value":-1,"anger":"Haha, you’re cute. I gave you one job. I can take it away, too."},
	"Blueprints Needed":{"from":"Winston Rizzo", "email":"wrizzo@digs.org", "text":"Greetings. Me and the boys started renovating the 3rd floor bathrooms and then realized we didn’t have the blueprints. We’ve already got a couple unusable toilets and a pair of soiled trousers on our hands. Please forward this to the boss so he can send those blueprints our way.\n\n– Winston Digs, Maintenance", "links":"","value":1,"anger":"Hey, what happened to the bathrooms?! Someone should’ve told me something!"},
	"Wet Floor Signs":{"from":"Winston Rizzo", "email":"wrizzo@digs.org", "text":"Salutations. We’ve run out of wet floor signs and I’m worried someone is going to slip on all of this water at some point. We just dodged a big lawsuit and I know we don’t want another one on your hands. Get us more signs ASAP.\n\n– Winston Digs, Maintenance", "links":"","value":1,"anger":"Apparently one of our clients slipped on an unmarked wet floor. Winston should’ve asked me for more signs!"},
	"sick today":{"from":"Katherine McGill", "email":"kmcgill@digs.org", "text":"sup. cant come in to work, got the black death or somethin. forgot what doctor called it. tell boss pls. kat.\n\n-- Katherine McGill, Marketing","links":"","value":1,"anger":"Where’s Katherine? Did she try to tell me I was sick? I need to know these things!"},
	"new slogan":{"from":"Katherine McGill", "email":"kmcgill@digs.org", "text":"boss asked me for new slogan for DIGS. here it is: “we make toxic metals fun”. kids will love it. kat.\n\n-- Katherine McGill, Marketing","links":"","value":1,"anger":"Either Katherine has hit some serious writer’s block or you didn’t send me that slogan I need from her."},
	"Internship Thingy":{"from":"Molly Chase", "email":"mchase@digs.org", "text":"Heyyyy this is Molly from HR and apparently the boss man wants to do some internship thingy? He said something about getting lots of kids to go into the mines with their nimble bodies and I need help putting together an application for the position. Can I meet with him pretty please?\n\nkthxbye #blessed\n-- Molly Chase, Human Resources","links":"","value":1,"anger":"My top-secret internship program is nowhere close to seeing the light of day. Where’s Molly?"},
	"Complaints":{"from":"Molly Chase", "email":"mchase@digs.org", "text":"Yo yo yo, Chase is up in your biz! You know who is up in my biz? Bert from I.T.! He keeps saying something about funny tasting water. He’s a major bummer. He went ahead and filed a complaint and boss man needs to give it a looksie ASAP.\n\nlaterz #slayeveryday\n–- Molly Chase, Human Resources","links":"Here’s The PDF (digs-complaint-form-92845.pdf)","value":1,"anger":"I’ve noticed a large decrease in the number of complaints I’m receiving. You’re sending me all of Molly’s complaint forms, right?"},
	"Mercury.":{"from":"Bert Samson", "email":"bsamson@digs.org", "text":"Mercury is coming out of the 3rd floor drinking fountain. Winston said it’s fine. It is not. Do something about it.\n\n--Bert Samson, Information Technology","links":"","value":1,"anger":"Bert is pounding on my door. I’m scared. Usually he gives me a warning before he gets aggressive like this…"},
	"Hacked.":{"from":"Bert Samson", "email":"bsamson@digs.org", "text":"Apparently some of our employees have been clicking on dubious emails, because our company network is hacked. Trying to get it fixed. Tell people to use common sense.\n\n--Bert Samson, Information Technology","links":"","value":1,"anger":"Bert is pounding on my door. I’m scared. Usually he gives me a warning before he gets aggressive like this…"},
	"Signature Required":{"from":"Sierra Valentino", "email":"valentinolaw@legal.gov", "text":"Good day to you. I’m pleased to inform you that the lawsuit against your company for dumping illegal quantities of mercury in the water supply has been settled. I just need a signature from one of your superiors and we’ll be good to go.\n\nPleasure doing business with you.\n--Sierra Valentino.","links":"Link to Form (valentinolaw.gov)","value":1,"anger":"The feds are still whining about that mercury fiasco. Didn’t we get that case settled?"},
	"New Expansions":{"from":"Sierra Valentino", "email":"valentinolaw@legal.gov", "text":"Yello! I’m Mr. Minings, a recent investor and soon-to-be franchise owner of our own local DIGS Inc. location! I spoke to the boss last night regarding expanding the Mercury mining, and since my hometown has untapped potential, I would like to schedule a meeting with him. Included is a link to the site plans that I had developed (officially this time, might I add!)","links":"Image Link (hometown_mercury.jpeg)","value":1,"anger":"Have you heard from Mr. Minings recently? I met him in a pub last night and he seemed interested in helping the business!"},
	"Lead Shipment Delayed":{"from":"Garrison Weiser", "email":"gweiser@eatlead.com", "text":"Is not good day. Motherland hit by blizzard. No lead for you today. Track shipment with fancy link.","links":"Lead Tracking (www.leadmetolead.net)","value":1,"anger":"Our lead supply is looking awfully dry. I’ll bet something went wrong with our shipment. Did Garrison reach out to you?"},
	"Calendar Addition: New Employee Interview":{"from":"DIGS IMS", "email":"digsnetwork@digs.org", "text":"*This email is an automated message from the DIGS Internal Management System*\n\nA new calendar date has been added to the user: “Stephen Careers”.\nDetails:\n\nDesc - Desc - “New Hire for Mercury Taste Testing”\nDate - 02/10/2025\nTime - 6:30am - 8:00am","links":"View Calendar (www.calendar.digs.com)","value":1,"anger":"I was hoping to get a reminder about the Mercury Taste Tester we were looking to hire, did you happen to get the auto message thingy?"},
	"Doctor's Appointment":{"from":"Dr. Telia", "email":"ytelia@fmail.com", "text":"You signed up for notifications from SpringField Hospital.\nA reminder that you have an appointment scheduled with Dr. Telia for 10:00am Wednesday morning.","links":"","value":1,"anger":"I needed that reminder, why would you delete it?"},
	"Mules":{"from":"Jame Fily", "email":"jfily@fmail.com", "text":"Some of the mules need to be taken out of these mines. They are getting too old to be pulling carts anymore.","links":"","value":1,"anger":"Send me these emails in the future. Those mules need to be taken care of when they start to get old."},
	"Contract Proposal":{"from":"Jimmy James", "email":"jjames@fmail.com", "text":"I would like to buy Mercury from your company for some time, about 4 tons a month if possible. Do you know how much that would cost?","links":"","value":1,"anger":"Why would you turn down a potential customer?!"},
	"WHO DOESN'T LOVE MONEY?":{"from":"Richie Rich", "email":"getrichquick@bigmoney.com", "text":"HEY YOU! YES YOU! RICHES GALORE ARE IN STORE! FOR ONE LOW PRICE OF YOUR CREDIT CARD INFORMATION, ALL OF YOUR DREAMS WILL COME TRUE!","links":"CLICK ME FOR $$$ (scamming4dummies.com)","value":-1,"anger":"Come on, that was the most obvious scam in the world. Pay more attention!"},
	"Forgot Password":{"from":"Bert Samson", "email":"bsamson@bigs.com", "text":"Hey boss, I forgot the password to the server. Could you send it my way so I can run a security check on our network? Thanks in advance.\n\n--Bert Samson, Information Technology","links":"","value":-1,"anger":"That guy was posing as our I.T. specialist! Make sure to double-check everyone’s emails."},
	"Key Card Stopped Working":{"from":"Winston Rizzo", "email":"wrizz0@digs.org", "text":"My key card stopped working. I talked to Bryan in I.T. and he couldn’t fix it. Please send a working keycard to this address: 101 West Sneaky Street.\n\n--Winston Rizzo, Accounting","links":"","value":-1,"anger":"That email was bogus! Bert works in I.T., not Bryan. Also, Winston works in Maintenance, not Accounting. Pay more attention to our employee roster!"},
	"Package Delivery":{"from":"Bert Kamble", "email":"bkamble@amazing.com", "text":"Your Amazing package has arrived at DIGS inc. Please confirm your order.","links":"Confirm Here. (amazing.stealingYourMoney.io)","value":-1,"anger":"Did you even look at the email? Check the link, email, and name of sender next time."},
	"Kids acting up in School!":{"from":"Mercu-City Public Schools ","email":"mercucitygov@school.edu","text":"Hello, this is the principal of Mercu-City Public Schools writing to state that your kids are causing big trouble in class. Click the link provided to see a recent report made for them. Thank you.","links":"View Report (www.mercutownscoolreport.com)","value":-1,"anger":"Not only is that link suspicious, I also have no kids! And if I did, they would be working in my Mercury mines!"},
	"EMERGENCY! COMPROMISED EMAIL!":{"from":"EmailRecoveryServices","email":"loggetters@selfhosting.org","text":"WARNING! YOUR EMAIL HAS BEEN FOUND IN A RECENT DATA BREACH!\n\nWe advise you to quickly change your email and password using the form below:","links":"Link (www.loggetters.gov.com/form)","value":-1,"anger":"Woah, watch what you send me! I almost had a heart attack seeing this, and would of fallen for it if I wasn’t as smart as I am!"},
	"Locked Outside":{"from":"Careers Stephan","email":"scares@digs.org","text":"Well hello there! I lost my key card at a recent asbestos meeting, and I can’t seem to enter. I know I’m pretty mean on you, especially after that “company party” last week, but I’ll consider a raise for you if you just slip a card under the door!\n\nTo the best Secretary  in the world!\n--Your Manager, Careers Stephan","links":"","value":-1,"anger":"Not only did they get my name mixed up, they also couldn’t even get our products right! I don’t know how you thought this was me, but the chances of that raise have greatly dropped!"},
	"An Amazing Investment Opportunity!":{"from":"Mercury Duplicators Incorporated","email":"mercury@mdi.org","text":"Hello, We are writing to you today to notify you of an amazing investment opportunity. Our brand new company, Mercury Duplicators Incorporated, has discovered a way to make more mercury from your current stocks of mercury! All we need, to provide such an amazing deal to you, is your help funding $150,000 our expansion. If you do, we will provide free access to our services with your donation after we get everything working on our end. For security, we will need to be paid in crypto, in which our account is provided below:","links":"Here (www.seencocrypto.com/mercurycoinmakers )","value":-1,"anger":"I could already tell this was a scam, not because of the email, but because we’ve already spent four times that amount in research into the same thing!"},
	"Cat Toys":{"from":"Winston Ferlin","email":"wferlin@kissycat.com","text":"Your Cat Toys have been delivered to your apartment. Thanks for choosing Kissy Kat.","links":"","value":-1,"anger":"While cats are nice, I don’t need to know about your personal deliveries."},
	"First Day":{"from":"Mom","email":"proudmama@fmail.com","text":"Hi honey!! I just wanted to say that I’m SOOO proud of you for getting your secretary job and that I hope you’re doing great on your first day! Please call me if you need anything.\n\n--XOXO Mom","links":"","value":-1,"anger":"Your mom sounds sweet, but I don’t care to see her emails in my inbox. Unless she’s single."},
	"Gerald MISSING!":{"from":"Mom","email":"proudmama@fmail.com","text":"And hello to you my little munchkin! It seems like we have a problem: I can’t find Gerald anywhere! I mean, how does a turtle even escape like that? They’re too stinking slow! Be on the lookout for him. Who knows, maybe he wanted to protect you during your fancy new job. Oh, wait, I just found him! He was hiding under the bush in his atrium. I’m still sending you this so you know what happened. Love ya!\n\n--XOXO Mom","links":"","value":-1,"anger":"Why did I need to know about this? I mean, I’m glad she found Gerald, but this has nothing to do with DIGS affairs."},
	"Dinner Tonight":{"from":"Mom","email":"proudmama@fmail.com","text":"I’m trying to decide what to do for dinner tonight to celebrate your first day on the job. What do you think? Should we order a pizza? Go to a steakhouse? Maybe have some fish tacos? Call me and let me know what you want!\n\n--XOXO Mom","links":"","value":-1,"anger":"If it were up to me, I’d go for the steakhouse. Anyway, don’t send me this junk."},
	"*No Subject Provided*":{"from":"Dark Krow","email":"darkKrow17@fmail.com","text":"Hey, we played together yesterday. Give me your account info and I'll gift you $$$","links":"","value":-1,"anger":"Please do not get us involved in pathetic catfishing attempts."},
	"Lawn Mowing":{"from":"Fred Green","email":"fgreen98@fmail.com","text":"Do you need your yard mowed? Call 555-555-5555 and we can sign you up to get your lawn mowed every two weeks for the cheap price of $25 a month.","links":"Or Sign Up Here (www.letsgogreen.org)","value":-1,"anger":"Silly secretary, we haven't had grass around our establishment for 15 years. Too much gunk in the water."},
	"Account Creation Successful":{"from":"Bosder Customer Support","email":"customersupport-noreply@bosder.com","text":"Hello Stephen Careers! Your account for Bosder, the sophisticated dating site for only the best of bosses, has been successfully created with the email “scareers@digs.org”. We can’t wait to see you out and leading in both your career, and your love life!","links":"","value":-1,"anger":"Hey now! That is my private information that you’re reading there! At the very least, don’t let me know you’ve seen it."},
	"Void":{"from":"","email":"","text":"","links":"","value":0,"anger":"???"},
	#"Subject":{"from":"","email":"","text":"","links":"","value":-1,"anger":""},
}
var emailSize = emails.size()
var currentSubject = "Void"
var correctEmails = 0
var incorrectEmails = 0
